// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhYcC1Fm9GIpsP3PzIj3rXe0tJ23O5NU',
    appId: '1:568260240493:web:a606974902e23090b74b64',
    messagingSenderId: '568260240493',
    projectId: 'flutter-chat-app-21e48',
    authDomain: 'flutter-chat-app-21e48.firebaseapp.com',
    storageBucket: 'flutter-chat-app-21e48.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbweTDjgmtENdGpGAXuG7blk-LrvNHyvs',
    appId: '1:568260240493:android:f2c0320185978029b74b64',
    messagingSenderId: '568260240493',
    projectId: 'flutter-chat-app-21e48',
    storageBucket: 'flutter-chat-app-21e48.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAUp-ncg7s3VQtMrztagrLRPQWHLiVVXo',
    appId: '1:568260240493:ios:5d5d367d27368b95b74b64',
    messagingSenderId: '568260240493',
    projectId: 'flutter-chat-app-21e48',
    storageBucket: 'flutter-chat-app-21e48.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAUp-ncg7s3VQtMrztagrLRPQWHLiVVXo',
    appId: '1:568260240493:ios:5d5d367d27368b95b74b64',
    messagingSenderId: '568260240493',
    projectId: 'flutter-chat-app-21e48',
    storageBucket: 'flutter-chat-app-21e48.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjhYcC1Fm9GIpsP3PzIj3rXe0tJ23O5NU',
    appId: '1:568260240493:web:3d1ae5911c611c86b74b64',
    messagingSenderId: '568260240493',
    projectId: 'flutter-chat-app-21e48',
    authDomain: 'flutter-chat-app-21e48.firebaseapp.com',
    storageBucket: 'flutter-chat-app-21e48.firebasestorage.app',
  );
}
